Update assemble

diff --git a/sti/bin/assemble b/sti/bin/assemble
--- a/sti/bin/assemble
+++ b/sti/bin/assemble
@@ -129,7 +129,17 @@ fi
 buildType=$(echo "${MAVEN_BUILD_PIPELINE_TYPE}" | tr [:upper:] [:lower:])
 
 if [ "${buildType}" == "true" ]; then
-
+  if [ $(ls ${DEPLOY_DIR}/*${APP_SUFFIX}.jar | wc -l) -gt 0 ]; then
+    echo "[INFO] Copying ${DEPLOY_DIR}/*${APP_SUFFIX}.jar into ${DEPLOY_DIR}/"
+    cp ${DEPLOY_DIR}/*${APP_SUFFIX}.jar ${DEPLOY_DIR}/
+    echo "[INFO] Application jar file is located in ${DEPLOY_DIR}/"
+  elif [ $(ls ${DEPLOY_DIR}/*${APP_SUFFIX}.war | wc -l) -gt 0 ]; then
+    echo "[INFO] Copying ${DEPLOY_DIR}/*${APP_SUFFIX}.war into ${DEPLOY_DIR}/"
+    cp ${DEPLOY_DIR}/*${APP_SUFFIX}.war ${DEPLOY_DIR}/    
+  else
+    echo "[ERROR] No app.jar file located in ${DEPLOY_DIR}"
+    exit 1
+  fi
 
 fi
 
